const { Router } = require("express");
const c = require("../controllers/projectsController");
const { authenticate, requireAdmin } = require("../middlewares/auth");
const router = Router();
router.get("/",          authenticate, c.index);
router.get("/:id",       authenticate, c.show);
router.post("/",         authenticate, requireAdmin, c.store);
router.put("/:id",       authenticate, requireAdmin, c.update);
router.delete("/:id",    authenticate, requireAdmin, c.destroy);
router.post("/:id/logo", authenticate, requireAdmin, ...c.uploadLogo);
module.exports = router;
